name: Flutter Web
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.COMMIT_SECRET}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release
        # 1. change path which exist lib/main.dart
      - run:
          # 2. change path to [existed lib/main.dart path]/build/web
          cd build/web
      - run:
          git init
      - run:
          # 3. change your email
          git config --global user.email abhidhamma91@gmail.com
      - run:
          # 4. change your name
          git config --global user.name abhidhamma
          git status
      - run:
          # 5. change your repository
          git remote add origin master
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f